name: ?? Build and Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'  # Déclenche sur les tags de version (ex: v1.2.0)
  workflow_dispatch:  # Permet l'exécution manuelle
    inputs:
      version:
        description: 'Version to publish (leave empty to use csproj version)'
        required: false
        type: string

env:
  DOTNET_VERSION: '9.0.x'
  PROJECT_PATH: './Blazor.FlexLoader.csproj'
  PACKAGE_OUTPUT_DIRECTORY: './bin/Release'

# Permissions nécessaires pour créer des releases
permissions:
  contents: write
  packages: write
  actions: read

jobs:
  build-and-test:
    name: ?? Build & Test
    runs-on: ubuntu-latest
    
    steps:
    - name: ?? Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Récupère tout l'historique pour GitVersion
    
    - name: ?? Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: ?? Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
    
    - name: ?? Build project
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore /p:ContinuousIntegrationBuild=true
    
    - name: ?? Run tests (if any)
      run: |
        if [ -d "tests" ] || [ -d "test" ] || [ -d "Tests" ]; then
          dotnet test --configuration Release --no-build --verbosity normal
        else
          echo "?? No test projects found"
        fi

  publish-nuget:
    name: ?? Publish to NuGet
    needs: build-and-test
    runs-on: ubuntu-latest
    # Se déclenche si c'est un tag OU une exécution manuelle
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: ?? Checkout repository
      uses: actions/checkout@v4
    
    - name: ?? Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: ?? Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
    
    - name: ?? Build project
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore /p:ContinuousIntegrationBuild=true
    
    - name: ?? Create NuGet package
      run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
    
    - name: ?? Verify NuGet API key
      shell: bash
      run: |
        if [ -z "${{ secrets.NUGET_API_KEY }}" ]; then
          echo "? NUGET_API_KEY secret is not set. Configure it in repository Settings > Secrets and variables > Actions."
          exit 1
        fi
        echo "? NUGET_API_KEY is configured"
    
    - name: ?? Publish to NuGet.org
      run: |
        dotnet nuget push "${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg" \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    
    - name: ?? Publish symbols to NuGet.org
      run: |
        dotnet nuget push "${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.snupkg" \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate || true
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    
    - name: ?? Extract version from tag
      id: version
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            # Extraire la version du fichier .csproj
            VERSION=$(grep -oP '<Version>\K[^<]+' ${{ env.PROJECT_PATH }})
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          fi
        else
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        fi
    
    - name: ?? Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## ?? Blazor.FlexLoader ${{ steps.version.outputs.VERSION }}
          
          ### ?? NuGet Package
          ```bash
          dotnet add package Blazor.FlexLoader --version ${{ steps.version.outputs.VERSION }}
          ```
    
          ### ?? Installation
          ```csharp
          // Program.cs
          builder.Services.AddBlazorFlexLoader();
          ```
  
          ### ?? Links
          - ?? [NuGet Package](https://www.nuget.org/packages/Blazor.FlexLoader/${{ steps.version.outputs.VERSION }})
          - ?? [Documentation](https://github.com/daniwxcode/Blazor.FlexLoader#readme)
          - ?? [Detailed Guide](https://github.com/daniwxcode/Blazor.FlexLoader/blob/main/docs/LoaderService-Documentation.md)
          
          See [CHANGELOG.md](https://github.com/daniwxcode/Blazor.FlexLoader/blob/main/CHANGELOG.md) for detailed changes.
        files: |
          ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg
          ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.snupkg
        draft: false
        prerelease: false
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: ?? Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-published-artifacts
        path: ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*
        retention-days: 30